### ISSUE TITLE
Problem with getting data from Set<String>

### ISSUE THREAD

**Issue by SavinMike** [yandextaxitech/binaryprefs#30]
I'm trying to save bundle to binaryPrefs for that I'm recursively saving <key, value> to Set\<String\> and adding separator to key for saving deep of bundle data. But when i try to get data from this set sometimes i catch next error:

> key's value is zero bytes for deserialize  at com.ironz.binaryprefs.task.FutureBarrier.completeBlockingWithResultUnsafe(FutureBarrier.java)
>   at com.ironz.binaryprefs.init.LazyFetchStrategy.fetchCacheCandidates(LazyFetchStrategy.java)
>                                                                           getInternal(LazyFetchStrategy.java)
>   at com.ironz.binaryprefs.init.LazyFetchStrategy.getValue(LazyFetchStrategy.java)
>                                                                           getAll(LazyFetchStrategy.java)
>                                                                           contains(LazyFetchStrategy.java)
>                                                                           access$000(LazyFetchStrategy.java)
>   at com.ironz.binaryprefs.BinaryPreferences.getAll(BinaryPreferences.java)

**Comment by iamironz** [comment]
Hi Mike!
Thanks for submitting the issue. I will solve your problem ASAP.
--
Regards,
Alexander

**Comment by iamironz** [comment]
Mike please can you provide binaryprefs version, builder which is defined preferences configuration and an code which saves `Set<String>`.

Regards,
Alenxander

**Comment by SavinMike** [comment]
Binaryprefs version is 1.0.0-BETA-2

```
new BinaryPreferencesBuilder(context)
				.name(DEFAULT_PREFS)
				.supportInterProcess(false)
				.exceptionHandler(exceptionHandler)
				.build();
```

**Comment by iamironz** [comment]
Can you please show me code which saves preferences recursively?
