### ISSUE TITLE
Encryption key update

### ISSUE THREAD

**Issue by IamEgor** [yandextaxitech/binaryprefs#45]
Hello! Thanks for this library.
What is the best way to update encryptionkey for keyEncryption and valueEncryption?

**Comment by iamironz** [comment]
Hey. 
If you wanna to migrate all data to another preferences instance without data lost you should use migration mechanism which described [here].(https://github.com/yandextaxitech/binaryprefs#migration-from-another-implementations)

Just create a new preferences with another name and key/value encryption keys and migrate all your old data to new one.

Cheers.

**Comment by IamEgor** [comment]
I've already try that and have an exception: 
Caused by: com.ironz.binaryprefs.exception.FileOperationException: java.io.FileNotFoundException: /data/user/0/com.covrsecurity.covr.test/files/preferences/corv_safe_storage/values/cdt7cy32cnt66x3ndsy7wxbmfm: open failed: ENOENT (No such file or directory)

**Comment by iamironz** [comment]
Are you sure you are using api correctly?

Check this out sample from tests: 

https://github.com/yandextaxitech/binaryprefs/blob/master/library/src/test/java/com/ironz/binaryprefs/migration/MigrateProcessorTest.java#L53-L78

**Comment by iamironz** [comment]
Outdated
