### ISSUE TITLE
Can't create preferences directory in /mnt/expand/

### ISSUE THREAD

**Issue by dkrivoruchko** [yandextaxitech/binaryprefs#54]
Library version: 1.0.1
Android version: 6.0, 6.01, 7.1.1, 8.10
Devices: Many different vendors

`RuntimeException: Unable to create service  due to error :
		Can't create definition for 'Single [name='e',class='com.ironz.binaryprefs.e']' due to error :
		Can't create preferences directory in /mnt/expand/48c4be18-bd88-491e-a0ac-d6aaedfe1df9/user/0/info.dvkr.screenstream/files/preferences/default/values
		com.ironz.binaryprefs.e.b.a.a(AndroidDirectoryProvider.java:40)
		com.ironz.binaryprefs.e.b.a.<init>(AndroidDirectoryProvider.java:31)
		com.ironz.binaryprefs.b.b(BinaryPreferencesBuilder.java:1266)
`

Common thins is that directory starts from: `/mnt/expand/`

**Comment by iamironz** [comment]
Hello. Sorry for the long answer. I dunno what directory you using for but in normal cases there this kind of problem implies not from binaryprefs library. Please, review your code. Although it might be an specific platform bug.
