### ISSUE TITLE
In-memory cache of byte array is vulnerable for external modifications

### ISSUE THREAD

**Issue by tujhex** [yandextaxitech/binaryprefs#57]
Hi. When write/read byte arrays, lib uses in-memory cache. But if you get those array, and modify it - cache also modifies, because you have the same reference. 
I encountered that when I tried to clear some fetched data with `new Random().nextBytes(data)` after usage.

**Comment by iamironz** [comment]
Hi! Thank you for submitting, I'll fix this issue ASAP.

**Comment by otopba** [comment]
@iamironz 14 May 2019 ASAP =)  Any updates?

**Comment by iamironz** [comment]
Already fixed
